/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct minifyjpeg_input {
	struct {
		u_int src_len;
		char *src_val;
	} src;
};
typedef struct minifyjpeg_input minifyjpeg_input;

struct minifyjpeg_output {
	struct {
		u_int dst_len;
		char *dst_val;
	} dst;
};
typedef struct minifyjpeg_output minifyjpeg_output;

#define MINIFYJPEG_PROG 0x31234567
#define MINIFYJPEG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINIFYJPEG_PROC 1
extern  enum clnt_stat minifyjpeg_proc_1(minifyjpeg_input , minifyjpeg_output *, CLIENT *);
extern  bool_t minifyjpeg_proc_1_svc(minifyjpeg_input , minifyjpeg_output *, struct svc_req *);
extern int minifyjpeg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINIFYJPEG_PROC 1
extern  enum clnt_stat minifyjpeg_proc_1();
extern  bool_t minifyjpeg_proc_1_svc();
extern int minifyjpeg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_minifyjpeg_input (XDR *, minifyjpeg_input*);
extern  bool_t xdr_minifyjpeg_output (XDR *, minifyjpeg_output*);

#else /* K&R C */
extern bool_t xdr_minifyjpeg_input ();
extern bool_t xdr_minifyjpeg_output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
