/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"

bool_t
xdr_minifyjpeg_input (XDR *xdrs, minifyjpeg_input *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->src.src_val, (u_int *) &objp->src.src_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_minifyjpeg_output (XDR *xdrs, minifyjpeg_output *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->dst.dst_val, (u_int *) &objp->dst.dst_len, ~0))
		 return FALSE;
	return TRUE;
}
